name: Firebase Deployment

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build
        env:
          CI: false
        run: yarn build

      - name: Verify Build Directory
        run: ls -lah dist/ || echo "⚠️ Dist directory not found!"

      - name: Archive Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/
          if-no-files-found: error

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist

      - name: Set up Firebase authentication
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/service-account.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/service-account.json" >> $GITHUB_ENV

      - name: Deploy to Firebase (Staging)
        if: github.ref == 'refs/heads/staging'
        run: firebase deploy --only hosting:staging --project admin-template-77844

      - name: Deploy to Firebase (Production)
        if: github.ref == 'refs/heads/main'
        run: firebase deploy --only hosting:production --project admin-template-77844